/**
 * Verifies the per-folder README.md files under src/ still describe what is
 * actually on disk.
 *
 *   npm run check:docs
 *
 * Why this exists: folder docs die the same way every time. Someone adds a
 * module, nobody updates the table, and six months later the doc is confidently
 * wrong — which is worse than having no doc, because it gets trusted. The prose
 * in those files cannot be checked by a machine, but the file table can, and the
 * table is what a change scan reads first.
 *
 * So: every documented folder must have a README.md whose `## Files` table lists
 * exactly the source files present, no more and no less. src/README.md is
 * checked the same way against its `## Folders` table.
 *
 * Two deliberate exceptions:
 *
 *   - src/vendor/ is existence-only. Its contents are regenerated by
 *     `npm run vendor` and the filenames are the extractor's business; an engine
 *     upgrade must not fail the docs gate.
 *   - src/sidepanel/components/ has no doc of its own. Its files are expected in
 *     the parent table with a `components/` prefix, because four small Preact
 *     components do not warrant a second file.
 *
 * Reports every problem at once — a first-failure-only check turns one fix into
 * five runs.
 */
import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Extensions that count as source worth documenting. */
const SOURCE = ['.ts', '.tsx', '.html'];

/**
 * mode 'files'   — table must match the source files in the folder
 * mode 'folders' — table must match the subdirectories of the folder
 * mode 'exists'  — README.md must exist; contents not checked
 * merge          — subfolder whose files belong in this folder's table, prefixed
 */
const DOCUMENTED = [
  { dir: 'src', mode: 'folders' },
  { dir: 'src/background', mode: 'files' },
  { dir: 'src/content', mode: 'files' },
  { dir: 'src/core', mode: 'files' },
  { dir: 'src/engine', mode: 'files' },
  { dir: 'src/shared', mode: 'files' },
  { dir: 'src/sidepanel', mode: 'files', merge: ['components'] },
  { dir: 'src/vendor', mode: 'exists' },
];

const problems = [];
/** Paths are reported with forward slashes so they read the same on every OS. */
const fail = (where, message) => problems.push(`${where.replace(/\\/g, '/')}: ${message}`);

/**
 * Pulls the first column out of the markdown table under `## <heading>`.
 * Cells look like `` `rank.ts` `` or `` [`core/`](core/README.md) ``; both
 * reduce to the backticked label. Everything outside the table is free text.
 */
function tableEntries(markdown, heading) {
  const lines = markdown.split(/\r?\n/);
  const start = lines.findIndex((l) => l.trim() === `## ${heading}`);
  if (start === -1) return null;

  const entries = [];
  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith('## ')) break;
    if (!line.startsWith('|')) continue;

    const cell = line.split('|')[1]?.trim() ?? '';
    if (!cell || /^-+$/.test(cell)) continue; // separator row
    if (cell === 'File' || cell === 'Folder') continue; // header row

    const label = cell.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1'); // unwrap links
    const name = label.replace(/`/g, '').trim().replace(/\/$/, '');
    if (name) entries.push(name);
  }
  return entries;
}

/** Source files directly in `dir`, relative to it, optionally prefixed. */
function sourceFiles(dir, prefix = '') {
  return readdirSync(resolve(root, dir))
    .filter((name) => SOURCE.some((ext) => name.endsWith(ext)))
    .map((name) => prefix + name);
}

/** Subdirectories of `dir`. */
function subdirectories(dir) {
  return readdirSync(resolve(root, dir)).filter((name) =>
    statSync(resolve(root, dir, name)).isDirectory(),
  );
}

function compare(where, heading, documented, actual) {
  if (documented === null) {
    fail(where, `no "## ${heading}" table found`);
    return;
  }
  for (const name of actual) {
    if (!documented.includes(name)) {
      fail(where, `${name} exists but is not in the ${heading} table — add a row`);
    }
  }
  for (const name of documented) {
    if (!actual.includes(name)) {
      fail(where, `${heading} table lists ${name}, which is not on disk — remove the row`);
    }
  }
}

for (const { dir, mode, merge = [] } of DOCUMENTED) {
  const docPath = join(dir, 'README.md');

  if (!existsSync(resolve(root, docPath))) {
    fail(docPath, 'missing — every documented folder needs one');
    continue;
  }
  if (mode === 'exists') continue;

  const markdown = readFileSync(resolve(root, docPath), 'utf8');

  if (mode === 'folders') {
    compare(docPath, 'Folders', tableEntries(markdown, 'Folders'), subdirectories(dir));
    continue;
  }

  const actual = [
    ...sourceFiles(dir),
    ...merge.flatMap((sub) => sourceFiles(join(dir, sub), `${sub}/`)),
  ];
  compare(docPath, 'Files', tableEntries(markdown, 'Files'), actual);
}

if (problems.length > 0) {
  console.error(`check-docs: ${problems.length} problem(s)\n`);
  for (const problem of problems) console.error(`  ✗ ${problem}`);
  console.error('\nThe folder docs under src/ are the map a change scan reads first.');
  process.exit(1);
}

console.log(`check-docs: ok — ${DOCUMENTED.length} folder docs match disk`);
